swagger: '2.0'
info:
  version: 0.0.1
  title: EU Covid Certificate service for IO App
host: example.com
schemes:
  - https
paths:
  /certificate:
    post:
      operationId: getCertificate
      summary: Retrieve a certificate for a given Citizen
      description: |-
        Given a Citizen's fiscal code and an OTP (the auth code previously sent via IO Message), a Certificate is returned with ID, encoded QR-code, expiration date and a markdown text with all meaningful information to be shown to Citizens.
      parameters:
        - name: accessData
          in: body
          schema:
            $ref: "#/definitions/GetCertificateParams"
      responses:
        '200':
          description: |-
            A Certificate exists and it's found for the given access data. It is retrieved regardless of it's expired or its current status
          schema:
            $ref: "#/definitions/RawCertificate"
        '400':
          description: Payload has bad format
        '403':
          description: Access data provided are invalid or no Certificate has been emitted for the given Citizen
        '500':
          description: Generic server error
definitions:
  GetCertificateParams:
    type: object
    properties:
      fiscal_code:
        type: string
        description: fiscal code which identifies the Citizen requesting the Certificate
      auth_code:
        type: string
        description: OTP previously sent to the Citizen
    required:
      - fiscal_code
      - auth_code
  RawCertificate:
    type: string 
consumes:
  - application/json
produces:
  - application/json