swagger: '2.0'
info:
  title: OpenAPI definition
  version: v0
schemes:
  - https
basePath: /
paths:
  '/v1/certificate/citizen/{cfSHA256}':
    post:
      description: >-
        Servizio che restituisce un certificato a partire da AutCode e CF del
        cittadino.
      operationId: getCertificateByAutAndCF
      parameters:
        - in: path
          name: cfSHA256
          required: true
          type: string
        - in: query
          name: authCodeSHA256
          required: true
          type: string
      produces:
        - application/octet-stream
        - application/json
      responses:
        '200':
          description: Certificato trovato
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
        default:
          description: default response
          schema:
            $ref: '#/definitions/SearchSingleQrCodeResponseDTO'
      summary: Restituisce certificato
      tags:
        - Servizio dei Cittadini
  '/v1/certificate/citizen/{cfSHA256}/refresh':
    post:
      description: Servizio per comunicare un nuovo codice fiscale.
      operationId: managePreviousCertificates
      parameters:
        - in: path
          name: cfSHA256
          required: true
          type: string
      produces:
        - application/octet-stream
        - application/json
      responses:
        '200':
          description: Comunicazione avvenuta
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
        default:
          description: default response
          schema:
            $ref: '#/definitions/PreviousCertificateResponseDTO'
      summary: Comunica un nuovo codice fiscale
      tags:
        - Servizio dei Cittadini
definitions:
  ErrorResponseDTO:
    properties:
      code:
        description: Codice di errore
        format: int32
        type: integer
      message:
        description: Messaggio di errore
        type: string
    type: object
  PreviousCertificateResponseDTO:
    properties:
      data:
        format: int32
        type: integer
      error:
        $ref: '#/definitions/ErrorResponseDTO'
      keyDuplicate:
        type: string
      spanID:
        type: string
      traceID:
        type: string
    type: object
  QrCodeInfoDTO:
    properties:
      qrcode:
        description: Content del qrcode
        items:
          description: Content del qrcode
          format: byte
          type: string
        type: array
      uvci:
        description: UVCI
        type: string
    type: object
  SearchSingleQrCodeResponseDTO:
    properties:
      data:
        $ref: '#/definitions/QrCodeInfoDTO'
      error:
        $ref: '#/definitions/ErrorResponseDTO'
      keyDuplicate:
        type: string
      spanID:
        type: string
      traceID:
        type: string
    type: object

